WORKSPACE_PATH = 'Tensorflow/workspace'
SCRIPTS_PATH = 'Tensorflow/scripts'
APIMODEL_PATH = 'Tensorflow/models'
ANNOTATION_PATH = WORKSPACE_PATH+'/annotations'
IMAGE_PATH = WORKSPACE_PATH+'/images'
MODEL_PATH = WORKSPACE_PATH+'/models'
PRETRAINED_MODEL_PATH = WORKSPACE_PATH+'/pre-trained-models'
CONFIG_PATH = MODEL_PATH+'/my_ssd_mobnet/pipeline.config'
CHECKPOINT_PATH = MODEL_PATH+'/my_ssd_mobnet/'
CUSTOM_MODEL_NAME = 'my_ssd_mobnet'
CONFIG_PATH_1 = MODEL_PATH+'/'+CUSTOM_MODEL_NAME+'/pipeline.config'

from Setup_Path import WORKSPACE_PATH,SCRIPTS_PATH,APIMODEL_PATH,ANNOTATION_PATH,IMAGE_PATH,MODEL_PATH,PRETRAINED_MODEL_PATH,CONFIG_PATH,CHECKPOINT_PATH,CUSTOM_MODEL_NAME,CONFIG_PATH_1